openapi: 3.0.0
info:
  title: FinVerse Recommendation Service API
  description: API for providing personalized product recommendations to users
  version: 1.0.0
  contact:
    name: FinVerse Team

servers:
  - url: /api/v1
    description: Base API path

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the service
      operationId: checkHealth
      tags:
        - Health
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"

  /recommendations/products/{user_id}:
    get:
      summary: Get product recommendations for a user
      description: Returns personalized product recommendations for the specified user
      operationId: getProductRecommendations
      tags:
        - Recommendations
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user to get recommendations for
          schema:
            type: string
        - name: count
          in: query
          required: false
          description: Number of recommendations to return
          schema:
            type: integer
            default: 5
            minimum: 1
            maximum: 50
      responses:
        "200":
          description: List of recommended products
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductRecommendationsResponse"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /recommendations/refresh-model:
    post:
      summary: Refresh recommendation model
      description: Triggers a manual refresh of the recommendation model
      operationId: refreshModel
      tags:
        - Model Management
      responses:
        "200":
          description: Model refresh result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModelRefreshResponse"

components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          enum: [healthy, unhealthy]
        version:
          type: string
        timestamp:
          type: string
          format: date-time

    ProductRecommendationsResponse:
      type: object
      properties:
        user_id:
          type: string
        recommendations:
          type: array
          items:
            $ref: "#/components/schemas/ProductRecommendation"
        timestamp:
          type: string
          format: date-time

    ProductRecommendation:
      type: object
      properties:
        product_id:
          type: string
        name:
          type: string
        description:
          type: string
        score:
          type: number
          format: float
        category:
          type: string
        price:
          type: number
          format: float

    ModelRefreshResponse:
      type: object
      properties:
        success:
          type: boolean
        duration_seconds:
          type: number
          format: float
        timestamp:
          type: string
          format: date-time
        num_users:
          type: integer
        num_products:
          type: integer
        error:
          type: string

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        timestamp:
          type: string
          format: date-time

tags:
  - name: Health
    description: Health check endpoints
  - name: Recommendations
    description: Product recommendation endpoints
  - name: Model Management
    description: Model management and refresh endpoints
