version: '3.8'

services:
  recommendation-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finverse-recommendation-service
    volumes:
      - type: bind
        source: ./src
        target: /app/src
      - type: bind
        source: ./data
        target: /app/data
      - type: bind
        source: ./logs
        target: /app/logs
    ports:
      - "4003:4003"
    environment:
      - DEBUG=true
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=finverse_interactions
      - BANKING_SERVICE_URL=http://host.docker.internal:4001/api/v1
      - MODEL_REFRESH_INTERVAL=3600 # 1 hour
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - finverse-network
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "4003", "--reload"]
  rabbitmq:
    image: rabbitmq:3-management
    container_name: finverse-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - finverse-network

  mongo:
    image: mongo:6
    container_name: finverse-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - finverse-network

networks:
  finverse-network:
    name: finverse-network
    driver: bridge

volumes:
  mongo-data:
    driver: local
