version: "3.8"

services:
  recommendation-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finverse-recommendation-service
    volumes:
      - type: bind
        source: ./src
        target: /app/src
      - type: bind
        source: ./data
        target: /app/data
      - type: bind
        source: ./logs
        target: /app/logs
    ports:
      - "4003:4003"
    environment:
      - DEBUG=true
      - MONGO_URI=mongodb+srv://thiwanka2002sandakalum_db_user:z6k1Jcj4reXy2vzh@development.zrcuhrn.mongodb.net/?appName=development
      - MONGO_DB=finverse_interactions
      - BANKING_SERVICE_URL=http://host.docker.internal:4001/api/v1
      - MODEL_REFRESH_INTERVAL=3600 # 1 hour
      - RABBITMQ_URL=amqps://rswxsxlo:KYIM-YxQUD4KAtGV8Pfzk3xIcWtzX-rr@puffin.rmq2.cloudamqp.com/rswxsxlo
    networks:
      - finverse-network
    command:
      [
        "uvicorn",
        "src.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "4003",
        "--reload",
      ]
networks:
  finverse-network:
    name: finverse-network
    driver: bridge
