version: '3.8'

services:
  banking-service-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder # Use builder stage for development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/banking_service_dev
      - CORS_ORIGIN=*
      - ENABLE_REQUEST_LOGGING=true
    depends_on:
      - postgres-dev
    restart: unless-stopped
    volumes:
      - ./src:/app/src:ro # Mount source for development
      - ./prisma:/app/prisma:ro
      - node_modules:/app/node_modules
    command: npm run dev # Override to run in development mode

  postgres-dev:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=banking_service_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432" # Different port to avoid conflicts
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_dev_data:
  node_modules:
