server:
  port: 4002
  host: 0.0.0.0
  readTimeout: 10
  writeTimeout: 10
  idleTimeout: 120

mongodb:
  uri: mongodb://localhost:27017
  database: interaction_service
  collection: interactions

rabbitmq:
  uri: amqp://guest:guest@localhost:5672/
  interactionQueue: interactions
  productViewQueue: product_views
  comparisonQueue: comparisons
  searchQueue: searches
  exchangeName: interaction_events
  exchangeType: topic
  reconnectAttempts: 5
  reconnectDelay: 5

logging:
  level: info
  file: ""
