# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Banking Service API to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'apps/backend/banking-service-api/**'
      - 'packages/**'
      - '.github/workflows/main_banking-service.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build banking service
        working-directory: ./apps/backend/banking-service-api
        run: |
          pnpm build

      - name: Prepare deployment package
        run: |
          mkdir -p deployment-package
          cp -r apps/backend/banking-service-api/dist deployment-package/
          cp -r apps/backend/banking-service-api/node_modules deployment-package/ || echo "node_modules not found, will be installed on Azure"
          cp apps/backend/banking-service-api/package.json deployment-package/
          cp apps/backend/banking-service-api/prisma deployment-package/ -r || echo "prisma folder not found"
          
          # Create a simple package.json for production
          cat > deployment-package/package.json << EOF
          {
            "name": "banking-service-api",
            "version": "1.0.0",
            "main": "dist/index.js",
            "scripts": {
              "start": "node dist/index.js",
              "prisma:generate": "prisma generate"
            },
            "dependencies": $(cat apps/backend/banking-service-api/package.json | jq '.dependencies')
          }
          EOF

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: banking-service-app
          path: deployment-package/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: banking-service-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7EB4ABFD5A2346B88644896CFCC3DFD3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_265197E9673746AFB0D39E31AD45143B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_16E0719824B54DF09C76EAEFCDD575D5 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'banking-service'
          slot-name: 'Production'
          package: .
          startup-command: 'npm run prisma:generate && npm start'
          